PACKAGE_NAME="rtd1296"
PACKAGE_VERSION="0.1.6"

BUILT_MODULE_LOCATION[0]="clk/"
BUILT_MODULE_NAME[0]="rtk-clk-rtd129x-ctlr"
BUILT_MODULE_LOCATION[1]="clk/"
BUILT_MODULE_NAME[1]="rtk-clk-cgc"
BUILT_MODULE_LOCATION[2]="gpio/"
BUILT_MODULE_NAME[2]="gpio-rtd129x"
BUILT_MODULE_LOCATION[3]="hw_random/"
BUILT_MODULE_NAME[3]="rtd-rng"
BUILT_MODULE_LOCATION[4]="irqchip/"
BUILT_MODULE_NAME[4]="irq-rtd129x"
BUILT_MODULE_LOCATION[5]="net/"
BUILT_MODULE_NAME[5]="r8169"
BUILT_MODULE_LOCATION[6]="phy/"
BUILT_MODULE_NAME[6]="rtk-sata-phy"
BUILT_MODULE_LOCATION[7]="pinctrl/"
BUILT_MODULE_NAME[7]="pinctrl-rtd129x"
BUILT_MODULE_LOCATION[8]="rtc/"
BUILT_MODULE_NAME[8]="rtc-rtd119x"
BUILT_MODULE_LOCATION[9]="serial/"
BUILT_MODULE_NAME[9]="8250_rtk"
BUILT_MODULE_LOCATION[10]="usb/"
BUILT_MODULE_NAME[10]="dwc3-of-simple-rtk"
BUILT_MODULE_LOCATION[11]="watchdog/"
BUILT_MODULE_NAME[11]="rtd119x_wdt"

DEST_MODULE_LOCATION[0]="/updates/dkms"
DEST_MODULE_LOCATION[1]="/updates/dkms"
DEST_MODULE_LOCATION[2]="/updates/dkms"
DEST_MODULE_LOCATION[3]="/updates/dkms"
DEST_MODULE_LOCATION[4]="/updates/dkms"
DEST_MODULE_LOCATION[5]="/updates/dkms"
DEST_MODULE_LOCATION[6]="/updates/dkms"
DEST_MODULE_LOCATION[7]="/updates/dkms"
DEST_MODULE_LOCATION[8]="/updates/dkms"
DEST_MODULE_LOCATION[9]="/updates/dkms"
DEST_MODULE_LOCATION[10]="/updates/dkms"
DEST_MODULE_LOCATION[11]="/updates/dkms"

AUTOINSTALL="yes"
REMAKE_INITRD="yes"
