PACKAGE_NAME="rtd1296"
PACKAGE_VERSION="0.1.3"

BUILT_MODULE_LOCATION[0]="irqchip/"
BUILT_MODULE_NAME[0]="irq-rtd129x"
BUILT_MODULE_LOCATION[1]="clk/"
BUILT_MODULE_NAME[1]="rtk-clk-rtd129x-ctlr"
BUILT_MODULE_LOCATION[2]="clk/"
BUILT_MODULE_NAME[2]="rtk-clk-cgc"
BUILT_MODULE_LOCATION[3]="watchdog/"
BUILT_MODULE_NAME[3]="rtd119x_wdt"
BUILT_MODULE_LOCATION[4]="rtc/"
BUILT_MODULE_NAME[4]="rtc-rtd119x"
BUILT_MODULE_LOCATION[5]="pinctrl/"
BUILT_MODULE_NAME[5]="pinctrl-rtd129x"
BUILT_MODULE_LOCATION[6]="gpio/"
BUILT_MODULE_NAME[6]="gpio-rtd129x"
BUILT_MODULE_LOCATION[7]="usb/"
BUILT_MODULE_NAME[7]="dwc3-of-simple-rtk"

DEST_MODULE_LOCATION[0]="/updates/dkms"
DEST_MODULE_LOCATION[1]="/updates/dkms"
DEST_MODULE_LOCATION[2]="/updates/dkms"
DEST_MODULE_LOCATION[3]="/updates/dkms"
DEST_MODULE_LOCATION[4]="/updates/dkms"
DEST_MODULE_LOCATION[5]="/updates/dkms"
DEST_MODULE_LOCATION[6]="/updates/dkms"
DEST_MODULE_LOCATION[7]="/updates/dkms"

AUTOINSTALL="yes"
REMAKE_INITRD="yes"
