rtk-clk-cgc-y := rtk-clk-mmio-gate.o rtk-clk-gate-ctlr.o
rtk-clk-rtd129x-ctlr-y := rtk-clk-common.o rtk-clk-mmio-gate.o rtk-clk-mmio-mux.o rtk-clk-pll.o rtk-clk-rtd129x.o rtk-clk-ctlr.o

obj-m += rtk-clk-cgc.o
obj-m += rtk-clk-rtd129x-ctlr.o
